Move test/devel/* into test/
Makes things much simpler.

ZD can sort out which tests go to CPAN (if we go there).

diff --git a/test/setup b/test/setup
--- a/test/setup
+++ b/test/setup
@@ -19,3 +19,19 @@ reset-env() {
     fi
   done
 }
+
+assert-booktown-db() {
+  if `! pg-db-exists booktown`; then
+    run() {
+      hither \
+          --in=test/dataset/pg/booktown.sql \
+          --out=pg://hither:h1th3r@localhost:5432/booktown
+    }; RUN
+    (exit $retval) || diag "$stdout$stderr"
+  fi
+  if `! pg-db-exists booktown`; then
+    die "Can't create booktown db"
+  fi
+}
+
+# vim: set sw=2:
